version: "3"
services:
    ceibacool:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - objs:/root/nginx-1.19.6/objs
            - ./ngx_ceibacool_module:/root/ngx_ceibacool_module
        # stdin_open: true
        # tty: true
volumes:
    objs:
